<?php

namespace clagiordano\weblibs\browserinfo\tests;

use clagiordano\weblibs\browserinfo\BrowserInfo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-22 at 22:33:08.
 */
class BrowserInfoTest extends \PHPUnit_Framework_TestCase
{
    private $browserInfo = null;
    const LIST_PATH = "testsdata/browserInfo_sample_agents.txt";

    public function testgetBrowserInfo()
    {
        
        $this->assertFalse($this->browserInfo->identificationStatus());
        $this->browserInfo->printR();$this->assertInstanceOf(
                'clagiordano\weblibs\php\BrowserInfo', 
                $this->browserInfo->getBrowserInfo()
            );

    }

    public function testgetBrowserInfoForceUserAgent()
    {
        $this->browserInfo->setUserAgentString(
            "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; .NET CLR 3.5.30729)"
        );

        $this->assertInstanceOf(
                'clagiordano\weblibs\php\BrowserInfo', 
                $this->browserInfo->getBrowserInfo()
            );
        $this->assertTrue($this->browserInfo->identificationStatus());

    }

    public function testgetBrowserInfoCycleUserAgents()
    {
        $this->assertFileExists(self::LIST_PATH);
        $handle = fopen(self::LIST_PATH, "r");
        
        $userAgents = file(self::LIST_PATH);
        $this->assertInternalType('array', $userAgents);
        $this->assertTrue(count($userAgents) > 0);

        $tested = 0;
        $failed = 0;
        $notMatched = [];
        
        foreach ($userAgents as $agent) {
            $this->browserInfo->setUserAgentString($agent);
            $this->assertInstanceOf(
                'clagiordano\weblibs\php\BrowserInfo', 
                $this->browserInfo->getBrowserInfo()
            );
            
            $tested++;
            $status = $this->browserInfo->identificationStatus();

            if ($status === false) {
                $failed++;
                $notMatched[] = $agent;
            }
        }
        
        var_dump($notMatched);
        
        $this->assertEquals(
            0, 
            $failed, 
            "Failed identifications {$failed} / {$tested}"
        );
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->browserInfo = new BrowserInfo();
        $this->assertInstanceOf(
            'clagiordano\weblibs\php\BrowserInfo', 
            $this->browserInfo
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
